server:
  port: 7003
  servlet:
    context-path: /eureka-provider

spring:
  application:
    name: eureka-provider

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



